### ISSUE TITLE
Driver standing instead of constructor standing

### ISSUE THREAD

**Issue by bolyaolya** [jolpica/jolpica-f1#67] opened 2024-08-17 08:47 UTC
**Describe the bug**
In the Api Root View we see Driver standing instead of Constructor standing

**Screenshot**
![image_2024-08-17_114714677](https://github.com/user-attachments/assets/c40e5fed-cdb2-4820-bbcf-887b321b80ff)

**Comment by jolpica** [comment] 2024-08-17 09:29
duplicate of #57

**Closed by jolpica** 2024-08-17 09:29 UTC
Labels: bug
